// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4pa8UsqwrkDITbgKoaTmNIr3aLaIxzO4',
    appId: '1:649353689397:web:b8146155771eaf36a5347c',
    messagingSenderId: '649353689397',
    projectId: 'finalrafiq',
    authDomain: 'finalrafiq.firebaseapp.com',
    storageBucket: 'finalrafiq.firebasestorage.app',
    measurementId: 'G-VM9REJSSL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqwnB6QCSrY1aFjvZASzG5L9K2yuBF5A',
    appId: '1:649353689397:android:df99c8e4d09244d6a5347c',
    messagingSenderId: '649353689397',
    projectId: 'finalrafiq',
    storageBucket: 'finalrafiq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9chUiGCxo6GvyU94C412bjTZD79lAyA',
    appId: '1:649353689397:ios:44063b9588e61b1ba5347c',
    messagingSenderId: '649353689397',
    projectId: 'finalrafiq',
    storageBucket: 'finalrafiq.firebasestorage.app',
    iosBundleId: 'com.example.finalrafiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9chUiGCxo6GvyU94C412bjTZD79lAyA',
    appId: '1:649353689397:ios:44063b9588e61b1ba5347c',
    messagingSenderId: '649353689397',
    projectId: 'finalrafiq',
    storageBucket: 'finalrafiq.firebasestorage.app',
    iosBundleId: 'com.example.finalrafiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4pa8UsqwrkDITbgKoaTmNIr3aLaIxzO4',
    appId: '1:649353689397:web:4c2a89038ca8b41da5347c',
    messagingSenderId: '649353689397',
    projectId: 'finalrafiq',
    authDomain: 'finalrafiq.firebaseapp.com',
    storageBucket: 'finalrafiq.firebasestorage.app',
    measurementId: 'G-88723KF5PM',
  );
}
